apiVersion: v1
kind: Secret
metadata:
  name: plansync-secrets
  namespace: plansync
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk
  db-password: cm9vdHBhc3N3b3Jk
  jwt-secret: WkdWMkxXTm9ZVzVuWlMxdFpTMHpNaTFpZVhSbGN5MXRhVzFwYlhWdExYTmxZM0psZEE5PQ==
  smtp-password: c2RvZGJobWVkY2p3b2pudQ==
