apiVersion: v1
kind: ConfigMap
metadata:
  name: plansync-mysql-initdb
  namespace: plansync
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS plansync_db_user
      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE DATABASE IF NOT EXISTS plansync_projet_db
      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
