apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: projet-service-hpa
  namespace: plansync
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: projet-service
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
