apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: plansync-services
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - api-gateway.plansync.svc.cluster.local:8085
              - user-service.plansync.svc.cluster.local:8079
              - projet-service.plansync.svc.cluster.local:8082
              - config-server.plansync.svc.cluster.local:8888
              - eureka-server.plansync.svc.cluster.local:8761
