export interface QualityDashboardMetrics {
  totalAudits: number;
  plannedAudits: number;
  inProgressAudits: number;
  completedAudits: number;
  averageAuditScore: number;
  averageComplianceRate: number;
  totalNonConformities: number;
  openNonConformities: number;
  closedNonConformities: number;
  totalCorrectiveActions: number;
  pendingCorrectiveActions: number;
  completedCorrectiveActions: number;
  overdueCorrectiveActions: number;
}

export interface QualityDashboardSummary {
  metrics: QualityDashboardMetrics;
  recentAudits: QualityAudit[];
  recentNonConformities: NonConformity[];
  correctiveActionQueue: CorrectiveAction[];
}

export interface RegisterFaceProfileRequest {
  userId: number;
  faceDescriptor: number[];
}

export interface FaceProfileResponse {
  id?: number;
  userId: number;
  createdAt?: string;
  updatedAt?: string;
  hasProfile: boolean;
}

export interface VerifyAuditFaceRequest {
  auditId: number;
  userId: number;
  liveFaceDescriptor: number[];
}

export interface VerifyAuditFaceResponse {
  verified: boolean;
  distanceScore?: number | null;
  threshold: number;
  message: string;
  auditId: number;
  userId: number;
  verificationLogId?: number;
}

export interface AuditIdentityVerificationLog {
  id: number;
  auditId: number;
  userId: number;
  verified: boolean;
  distanceScore?: number | null;
  thresholdUsed: number;
  verifiedAt: string;
  failureReason?: string;
  verificationMethod: string;
}

export interface AuditHeatmapItem {
  groupId: number;
  groupName: string;
  groupType: 'PROJECT' | 'AUDIT' | 'STANDARD';
  totalNonConformities: number;
  criticalCount: number;
  highCount: number;
  mediumCount: number;
  lowCount: number;
  overdueCorrectiveActions: number;
  averageComplianceScore?: number | null;
  hotspotScore: number;
  hotspotLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  explanation: string;
}

export type InspectionResultStatus = 'PASS' | 'FAIL' | 'PARTIAL';

export interface QualityUserRef {
  id: number;
  firstName: string;
  lastName: string;
}

export interface QualityProjectRef {
  id: number;
  name: string;
}

export interface QualityStandardRef {
  id: number;
  code: string;
  name: string;
}

export interface QualityStandardRequest {
  code: string;
  name: string;
  description: string;
  category: string;
  sourceType: string;
  version: string;
  active: boolean;
  projectId: number;
  createdByUserId: number;
}

export interface QualityStandard {
  id: number;
  code: string;
  name: string;
  description?: string;
  category: string;
  sourceType: string;
  version: string;
  active: boolean;
  project?: QualityProjectRef;
  createdBy?: QualityUserRef;
  createdAt?: string;
  updatedAt?: string;
}

export interface StandardCriterion {
  id: number;
  title: string;
  description?: string;
  expectedValue?: string;
  weight: number;
  mandatory: boolean;
  orderIndex: number;
  qualityStandard?: QualityStandard;
  createdAt?: string;
  updatedAt?: string;
}

export interface StandardCriterionRequest {
  title: string;
  description?: string;
  expectedValue?: string;
  weight: number;
  mandatory: boolean;
  orderIndex: number;
}

export interface QualityAuditRequest {
  title: string;
  description?: string;
  projectId: number;
  qualityStandardId?: number;
  auditType: string;
  status: string;
  plannedDate?: string;
  auditorUserId: number;
  createdByUserId: number;
}

export interface QualityAudit {
  id: number;
  title: string;
  description?: string;
  project?: QualityProjectRef;
  qualityStandard?: QualityStandardRef;
  auditType: string;
  status: string;
  plannedDate?: string;
  executionDate?: string;
  score?: number;
  complianceRate?: number;
  auditor?: QualityUserRef;
  createdBy?: QualityUserRef;
  closedAt?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface AuditChecklistItem {
  id: number;
  label: string;
  description?: string;
  status: string;
  observedValue?: string;
  comment?: string;
  weight: number;
  mandatory: boolean;
  reviewedAt?: string;
  qualityAudit?: QualityAudit;
  standardCriterion?: StandardCriterion;
  createdAt?: string;
  updatedAt?: string;
}

export interface InspectionRecordRequest {
  auditChecklistItemId: number;
  qualityAuditId?: number | null;
  observedValue: string;
  comment?: string;
  inspectorName: string;
  evidenceUrl?: string;
}

export interface InspectionRecord {
  id: number;
  observedValue: string;
  expectedValueSnapshot: string;
  resultStatus: InspectionResultStatus;
  comment?: string;
  inspectedAt: string;
  inspectorName: string;
  auditChecklistItemId: number;
  qualityAuditId: number;
  evidenceUrl?: string;
  autoGeneratedNonConformity: boolean;
}

export interface InspectionExecutionResponse {
  inspectionRecord: InspectionRecord;
  checklistItem: AuditChecklistItem;
  qualityAudit: QualityAudit;
  nonConformityCreated: boolean;
  nonConformityId?: number;
  nonConformityReferenceCode?: string;
  inspectionCountForItem: number;
  auditOpenNonConformityCount: number;
}

export interface NonConformity {
  id: number;
  referenceCode: string;
  title: string;
  description?: string;
  severity: string;
  status: string;
  detectedDate?: string;
  dueDate?: string;
  resolutionDate?: string;
  rootCause?: string;
  resolutionSummary?: string;
  project?: QualityProjectRef;
  reportedBy?: QualityUserRef;
  assignedTo?: QualityUserRef;
  createdAt?: string;
  updatedAt?: string;
}

export interface NonConformityAiSuggestionRequest {
  referenceCode?: string;
  title: string;
  description?: string;
  severity?: string;
  status?: string;
  detectedDate?: string;
  dueDate?: string;
  resolutionDate?: string;
  rootCause?: string;
  resolutionSummary?: string;
}

export interface NonConformityAiSuggestionResponse {
  probableRootCause: string;
  suggestedPriority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  suggestedCorrectiveActions: string[];
  reasoning: string;
}

export interface ApplyAiSuggestionRequest {
  title: string;
  description: string;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  actionType: 'CORRECTIVE';
  assignedToUserId?: number;
  createdByUserId?: number;
  dueDate?: string;
}

export interface HistoricalActionRecommendation {
  sourceCorrectiveActionId: number;
  recommendedTitle: string;
  recommendedDescription?: string;
  status?: string;
  priority?: string;
  actionType?: string;
  sourceNonConformityId: number;
  sourceNonConformityReferenceCode?: string;
  sourceNonConformityTitle?: string;
  sourceNonConformityDescription?: string;
  reason: string;
  score: number;
  rank: number;
}

export interface SmartCorrectiveActionRecommendation {
  nonConformityId: number;
  referenceCode: string;
  title: string;
  aiSuggestions: NonConformityAiSuggestionResponse;
  historicalRecommendations: HistoricalActionRecommendation[];
}

export interface CreateCorrectiveActionFromRecommendationRequest {
  sourceCorrectiveActionId?: number;
  title: string;
  description?: string;
  actionType: 'CORRECTIVE';
  priority?: string;
  assignedToUserId?: number;
  createdByUserId?: number;
  dueDate?: string;
}

export interface EvidenceScanResponse {
  evidenceSummary: string;
  detectedIssue: string;
  suggestedTitle: string;
  suggestedDescription: string;
  suggestedSeverity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  suggestedPriority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  suggestedCategory: string;
  probableRootCause: string;
  suggestedCorrectiveAction: string;
  reasoning: string;
  confidenceScore: number;
  extractedText?: string;
  sourceType: string;
  canCreateNonConformity: boolean;
}

export interface CreateNonConformityFromEvidenceRequest {
  auditId?: number | null;
  checklistItemId?: number | null;
  suggestedTitle: string;
  suggestedDescription?: string;
  detectedIssue?: string;
  suggestedSeverity: string;
  probableRootCause?: string;
  suggestedCategory?: string;
  assignedToUserId?: number;
  reportedByUserId?: number;
}

export interface CreateCorrectiveActionFromEvidenceRequest {
  title: string;
  description?: string;
  priority?: string;
  assignedToUserId?: number;
  createdByUserId?: number;
  dueDate?: string;
}

export interface MlNonConformityPredictionRequest {
  description: string;
}

export interface MlNonConformityPredictionResponse {
  predictedCategory: string;
  predictedPriority: string;
}

export interface CorrectiveAction {
  id: number;
  title: string;
  description?: string;
  actionType: string;
  status: string;
  priority: string;
  assignedTo?: QualityUserRef;
  startDate?: string;
  dueDate?: string;
  completionDate?: string;
  verificationComment?: string;
  createdBy?: QualityUserRef;
  nonConformity?: NonConformity;
  createdAt?: string;
  updatedAt?: string;
}

export interface QualityReport {
  id: number;
  title: string;
  executiveSummary?: string;
  overallScore?: number;
  complianceRate?: number;
  conclusion?: string;
  recommendations?: string;
  status: string;
  reportFileUrl?: string;
  approvedBy?: QualityUserRef;
  approvedAt?: string;
  qualityAudit?: QualityAudit;
  createdAt?: string;
  updatedAt?: string;
}

export interface ChecklistReviewPayload {
  status: string;
  observedValue?: string;
  comment?: string;
}
